import React from 'react'
import Link from 'next/link'
import { HiOutlineSparkles, HiOutlineBookOpen, HiOutlinePlay, HiOutlineShare } from 'react-icons/hi2'

function Hero() {
  return (
    <>
      {/* Hero Section */}
      <div className="relative overflow-hidden bg-gradient-to-b from-purple-50 to-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16 text-center">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary text-sm font-medium px-4 py-1.5 rounded-full mb-6">
            <HiOutlineSparkles className="text-base" />
            Powered by AI
          </div>

          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 leading-tight">
            Create Professional Courses
            <br />
            <span className="bg-clip-text bg-gradient-to-r from-purple-600 to-blue-600 text-transparent">
              in Minutes, Not Months
            </span>
          </h1>

          <p className="mt-6 text-lg md:text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            Describe your topic, and our AI generates a complete course with structured chapters,
            detailed content, code examples, and YouTube video recommendations — ready to share instantly.
          </p>

          <div className="mt-10">
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 bg-primary text-white text-base font-medium rounded-lg px-8 py-3.5 hover:bg-primary/90 transition-colors shadow-lg shadow-primary/25"
            >
              Start Creating for Free
              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="m9 18 6-6-6-6" />
              </svg>
            </Link>
          </div>
        </div>
      </div>

      {/* How It Works */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-center text-3xl font-bold text-gray-900 mb-4">How It Works</h2>
        <p className="text-center text-gray-500 mb-12 max-w-xl mx-auto">
          Go from idea to a fully structured course in three simple steps
        </p>

        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="w-12 h-12 bg-primary/10 text-primary rounded-xl flex items-center justify-center mx-auto mb-4 text-xl font-bold">1</div>
            <h3 className="font-semibold text-lg text-gray-900 mb-2">Describe Your Course</h3>
            <p className="text-gray-500 text-sm">
              Pick a category, enter your topic, choose difficulty level, and set the number of chapters.
            </p>
          </div>

          <div className="text-center">
            <div className="w-12 h-12 bg-primary/10 text-primary rounded-xl flex items-center justify-center mx-auto mb-4 text-xl font-bold">2</div>
            <h3 className="font-semibold text-lg text-gray-900 mb-2">AI Generates Content</h3>
            <p className="text-gray-500 text-sm">
              Our AI creates detailed chapters with explanations, code examples, and finds relevant YouTube videos.
            </p>
          </div>

          <div className="text-center">
            <div className="w-12 h-12 bg-primary/10 text-primary rounded-xl flex items-center justify-center mx-auto mb-4 text-xl font-bold">3</div>
            <h3 className="font-semibold text-lg text-gray-900 mb-2">Share & Learn</h3>
            <p className="text-gray-500 text-sm">
              Get a shareable link to your course. Anyone can access it and start learning right away.
            </p>
          </div>
        </div>
      </div>

      {/* Features */}
      <div className="bg-gray-50 py-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-center text-3xl font-bold text-gray-900 mb-12">What You Get</h2>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-10 h-10 bg-blue-100 text-blue-600 rounded-lg flex items-center justify-center mb-4">
                <HiOutlineSparkles className="text-xl" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-1">AI-Powered Content</h3>
              <p className="text-sm text-gray-500">Detailed explanations and code examples generated by GPT-4o</p>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-10 h-10 bg-purple-100 text-purple-600 rounded-lg flex items-center justify-center mb-4">
                <HiOutlineBookOpen className="text-xl" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-1">Structured Chapters</h3>
              <p className="text-sm text-gray-500">Well-organized curriculum with proper pacing and progression</p>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-10 h-10 bg-red-100 text-red-600 rounded-lg flex items-center justify-center mb-4">
                <HiOutlinePlay className="text-xl" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-1">Video Integration</h3>
              <p className="text-sm text-gray-500">Automatically finds relevant YouTube videos for each chapter</p>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-10 h-10 bg-green-100 text-green-600 rounded-lg flex items-center justify-center mb-4">
                <HiOutlineShare className="text-xl" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-1">Instant Sharing</h3>
              <p className="text-sm text-gray-500">Share your course with a single link — no signup needed to view</p>
            </div>
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-4">Ready to Create Your First Course?</h2>
        <p className="text-gray-500 mb-8 max-w-lg mx-auto">
          Join creators who are using AI to build courses faster than ever.
        </p>
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-2 bg-primary text-white text-base font-medium rounded-lg px-8 py-3.5 hover:bg-primary/90 transition-colors shadow-lg shadow-primary/25"
        >
          Get Started — It&apos;s Free
        </Link>
      </div>
    </>
  )
}

export default Hero
